# Uncomment the next line to define a global platform for your project
# platform :ios, '13'

target 'MovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieApp
pod 'Moya/RxSwift'
pod 'IQKeyboardManagerSwift'
pod 'lottie-ios'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                  config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
               end
          end
   end
end

